# Generated by Django 5.2.7 on 2025-10-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='guests_emails',
        ),
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='online_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
