# Generated by Django 5.2.7 on 2025-10-15 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_guest_event_privateevent_guest_event_private_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='event_private',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='event_public',
        ),
        migrations.AddField(
            model_name='guest',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='events.event'),
        ),
    ]
