# Generated by Django 5.2.7 on 2025-10-15 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_guest_event_private_remove_guest_event_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicevent',
            name='owner',
        ),
        migrations.DeleteModel(
            name='PrivateEvent',
        ),
        migrations.DeleteModel(
            name='PublicEvent',
        ),
    ]
