# Generated by Django 5.2.7 on 2025-10-26 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_guest_event_privateevent_guest_event_private_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Message de contact', 'verbose_name_plural': 'Messages de contact'},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'Invité', 'verbose_name_plural': 'Invités'},
        ),
        migrations.AlterModelOptions(
            name='privateevent',
            options={'verbose_name': 'Événement privé', 'verbose_name_plural': 'Événements privés'},
        ),
        migrations.AlterModelOptions(
            name='publicevent',
            options={'verbose_name': 'Événement public', 'verbose_name_plural': 'Événements publics'},
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('yes', 'Oui'), ('no', 'Non'), ('maybe', 'Peut-être')], default='yes', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_private', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.privateevent')),
                ('event_public', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.publicevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RSVP (Participation)',
                'verbose_name_plural': 'RSVPs (Participations)',
            },
        ),
    ]
