# Generated by Django 5.2.7 on 2025-11-18 00:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_contactmessage_options_alter_guest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Message de contact', 'verbose_name_plural': 'Messages de contact'},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='guest',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='privateevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='privateevent',
            name='image',
            field=models.ImageField(blank=True, help_text="Image de couverture de l'événement", null=True, upload_to='events/images/'),
        ),
        migrations.AddField(
            model_name='privateevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='publicevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='publicevent',
            name='image',
            field=models.ImageField(blank=True, help_text="Image de couverture de l'événement", null=True, upload_to='events/images/'),
        ),
        migrations.AddField(
            model_name='publicevent',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicevent',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre maximum de participants (laisser vide pour illimité)', null=True),
        ),
        migrations.AddField(
            model_name='publicevent',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Prix pour les événements payants', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='publicevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('declined', 'Décliné')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['email', 'status'], name='events_gues_email_9c9bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['token'], name='events_gues_token_e1dc1d_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['event_private', 'status'], name='events_gues_event_p_fe2578_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['event_public', 'status'], name='events_gues_event_p_b91cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['payment_status'], name='events_gues_payment_9808a9_idx'),
        ),
        migrations.AddIndex(
            model_name='privateevent',
            index=models.Index(fields=['owner', 'date'], name='events_priv_owner_i_10ae87_idx'),
        ),
        migrations.AddIndex(
            model_name='privateevent',
            index=models.Index(fields=['date'], name='events_priv_date_db93ac_idx'),
        ),
        migrations.AddIndex(
            model_name='publicevent',
            index=models.Index(fields=['owner', 'date'], name='events_publ_owner_i_2c87f8_idx'),
        ),
        migrations.AddIndex(
            model_name='publicevent',
            index=models.Index(fields=['date'], name='events_publ_date_17934c_idx'),
        ),
        migrations.AddIndex(
            model_name='publicevent',
            index=models.Index(fields=['is_paid'], name='events_publ_is_paid_048199_idx'),
        ),
        migrations.AddConstraint(
            model_name='guest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_private__isnull', False), ('event_public__isnull', True)), models.Q(('event_private__isnull', True), ('event_public__isnull', False)), _connector='OR'), name='guest_linked_to_one_event_type'),
        ),
        migrations.AddConstraint(
            model_name='rsvp',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_private__isnull', False), ('event_public__isnull', True)), models.Q(('event_private__isnull', True), ('event_public__isnull', False)), _connector='OR'), name='rsvp_linked_to_one_event_type'),
        ),
    ]
