# Generated by Django 5.2.7 on 2025-12-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_enable_2fa_for_all_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorauth',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='2FA activée'),
        ),
    ]
